POST http://localhost/api/users/receivePayment.php HTTP/1.1
content-type: application/json

{
    "Total": "120",
    "UniqueID": "danny15@mail.com",
    "CustomerEmail": "danny@mail.com"
}

###
POST http://stage.bibli.co.il/api/users/Credit.php HTTP/1.1
content-type: application/json

{
     "userid":"3906",
     "auth":"true",
     "username":"","price":8
}