export const CHOOSE_SUBSCRIPTION = "CHOOSE_SUBSCRIPTION";
export const SET_RETRIVED_DATE = "SET_RETRIVED_DATE";
export const GET_RECORDS_FROM_DB = "GET_RECORDS_FROM_DB";
export const DELETE_RECORD_FROM_USER = "DELETE_RECORD_FROM_USER";
export const INSERT_RECORD_TO_USER = "INSERT_RECORD_TO_USER";
export const ADD_USER = "ADD_USER";