export const CHOOSE_SUBSCRIPTION = "CHOOSE_SUBSCRIPTION";
export const SET_RETRIVED_DATE = "SET_RETRIVED_DATE";
export const GET_BIBLIST_NAMES_FROM_DB = "GET_BIBLIST_NAMES_FROM_DB";
export const DELETE_RECORD_FROM_USER = "DELETE_RECORD_FROM_USER";
export const INSERT_RECORD_TO_USER = "INSERT_RECORD_TO_USER";
export const ADD_USER = "ADD_USER";
export const INSERT_USER_TO_DB = "INSERT_USER_TO_DB";
export const GET_BIBLIST_FROM_DB = "GET_BIBLIST_FROM_DB";
export const USER_MAIL_VERIFICATION = "USER_MAIL_VERIFICATION";
export const ACTIVE_BIBLIST = "ACTIVE_BIBLIST";
export const LOGGED_IN = "LOGGED_IN";
export const DELETE_BIBLIST = "DELETE_BIBLIST";
export const BIB_SEARCH = "BIB_SEARCH";
export const GET_RECORD = "GET_RECORD";


